// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMGi-5TngsXz_GePIspuMHp7vyKp8GH0k',
    appId: '1:823148130413:web:0106fac2acd28de81a0f64',
    messagingSenderId: '823148130413',
    projectId: 'disan-store',
    authDomain: 'disan-store.firebaseapp.com',
    storageBucket: 'disan-store.firebasestorage.app',
    measurementId: 'G-5RZQ5HCGYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV_Cv7zHz3ibhPN3zXeG9CSup1m_yOf4E',
    appId: '1:823148130413:android:3a0b0d93635ccdb61a0f64',
    messagingSenderId: '823148130413',
    projectId: 'disan-store',
    storageBucket: 'disan-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBgt6iuTbTwijkpuN7Cz-eohcG1WqWG2w',
    appId: '1:823148130413:ios:41fcf1d984b8c0201a0f64',
    messagingSenderId: '823148130413',
    projectId: 'disan-store',
    storageBucket: 'disan-store.firebasestorage.app',
    iosBundleId: 'com.example.disan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBgt6iuTbTwijkpuN7Cz-eohcG1WqWG2w',
    appId: '1:823148130413:ios:41fcf1d984b8c0201a0f64',
    messagingSenderId: '823148130413',
    projectId: 'disan-store',
    storageBucket: 'disan-store.firebasestorage.app',
    iosBundleId: 'com.example.disan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMGi-5TngsXz_GePIspuMHp7vyKp8GH0k',
    appId: '1:823148130413:web:04cc9ac5584c5d411a0f64',
    messagingSenderId: '823148130413',
    projectId: 'disan-store',
    authDomain: 'disan-store.firebaseapp.com',
    storageBucket: 'disan-store.firebasestorage.app',
    measurementId: 'G-9KQYQLLGGH',
  );
}
